#!/usr/bin/env python3
"""
Export script: sync LEEF Datashare code vanuit vergunningcheck repo.

Extraheert de LEEF datashare routes, zaaktype mapping, database config,
logging config en HTML files uit de vergunningcheck repo naar de
standalone leef-datashare repo.

Gebruik:
    python export_from_vergunningcheck.py C:\vibecode\docchat\vergunningcheck
    python export_from_vergunningcheck.py ../vergunningcheck
"""
import sys
import os
import re
import shutil
import ast
from pathlib import Path


# === Constants ===
START_MARKER = "# === LEEF_DATASHARE_START ==="
END_MARKER = "# === LEEF_DATASHARE_END ==="

# Imports header voor leef_routes.py (standalone)
LEEF_ROUTES_IMPORTS = '''"""
LEEF Datashare Routes - Geexporteerd uit vergunningcheck/geo_api.py

Auto-generated by export_from_vergunningcheck.py. Do not edit manually.
"""
import os
import re
import json
import time
import base64
import hashlib
import asyncio
from io import BytesIO
from typing import Optional, List
from datetime import datetime, timedelta

from fastapi import APIRouter, HTTPException, Query, Request
from fastapi.responses import StreamingResponse, JSONResponse
from pydantic import BaseModel
import httpx

from db_config import get_connection, get_cursor, return_connection, execute_query, PLACEHOLDER
from logging_config import get_logger
from zaaktype_mapping import _ZAAKTYPE_MAPPING

logger = get_logger(__name__)

router = APIRouter(prefix="/geo", tags=["leef-datashare"])

'''

# HTML files die gekopieerd worden
HTML_FILES = [
    "leef_datashare.html",
    "classificatie_review.html",
    "classificatie_beheer.html",
    "classificatie_feedback.html",
    "classificatie_prompts.html",
]


def find_vergunningcheck_dir(arg: str) -> Path:
    """Vind de vergunningcheck directory."""
    p = Path(arg).resolve()
    if not p.exists():
        print(f"FOUT: Directory niet gevonden: {p}")
        sys.exit(1)
    # Check of geo_api.py bestaat
    if not (p / "geo_api.py").exists():
        print(f"FOUT: geo_api.py niet gevonden in {p}")
        sys.exit(1)
    return p


def extract_leef_block(geo_api_path: Path) -> str:
    """Extraheer het LEEF datashare blok tussen markers."""
    content = geo_api_path.read_text(encoding="utf-8")
    lines = content.split("\n")

    start_idx = None
    end_idx = None

    for i, line in enumerate(lines):
        if START_MARKER in line:
            start_idx = i + 1  # Na de marker
        if END_MARKER in line:
            end_idx = i  # Voor de marker

    if start_idx is None:
        print(f"FOUT: Start marker '{START_MARKER}' niet gevonden in geo_api.py")
        sys.exit(1)
    if end_idx is None:
        print(f"FOUT: End marker '{END_MARKER}' niet gevonden in geo_api.py")
        sys.exit(1)

    block = "\n".join(lines[start_idx:end_idx])

    # Vervang `@app.` met `@router.` voor standalone gebruik
    block = block.replace("@app.get(", "@router.get(")
    block = block.replace("@app.post(", "@router.post(")
    block = block.replace("@app.put(", "@router.put(")
    block = block.replace("@app.delete(", "@router.delete(")
    block = block.replace("@app.patch(", "@router.patch(")

    return block


def extract_zaaktype_mapping(geo_api_path: Path) -> str:
    """Extraheer de _ZAAKTYPE_MAPPING dict uit geo_api.py."""
    content = geo_api_path.read_text(encoding="utf-8")

    # Zoek het begin van _ZAAKTYPE_MAPPING
    match = re.search(
        r"^(_ZAAKTYPE_MAPPING\s*=\s*\{.*?^\})",
        content,
        re.MULTILINE | re.DOTALL,
    )
    if not match:
        print("WAARSCHUWING: _ZAAKTYPE_MAPPING niet gevonden, skip")
        return None

    mapping_code = match.group(1)
    return f"# Zaaktype mapping: TEAG_CODE -> (Omschrijving, Domein, Soort, Anse_code)\n{mapping_code}\n"


def copy_db_config(src_dir: Path, dest_dir: Path):
    """Kopieer db_config.py en strip SQLite branches."""
    src = src_dir / "db_config.py"
    dest = dest_dir / "db_config.py"

    if not src.exists():
        print(f"WAARSCHUWING: {src} niet gevonden, skip")
        return

    # Lees bestaande standalone versie als die er is (handmatig aangepast)
    if dest.exists():
        print(f"  db_config.py bestaat al, overslaan (handmatig beheerd)")
        return

    shutil.copy2(src, dest)
    print(f"  db_config.py gekopieerd (let op: bevat mogelijk SQLite code)")


def copy_logging_config(src_dir: Path, dest_dir: Path):
    """Kopieer logging_config.py met aangepaste service naam."""
    src = src_dir / "logging_config.py"
    dest = dest_dir / "logging_config.py"

    if not src.exists():
        print(f"WAARSCHUWING: {src} niet gevonden, skip")
        return

    if dest.exists():
        print(f"  logging_config.py bestaat al, overslaan (handmatig beheerd)")
        return

    content = src.read_text(encoding="utf-8")
    content = content.replace("vergunningcheck-api", "leef-datashare-api")
    dest.write_text(content, encoding="utf-8")
    print(f"  logging_config.py gekopieerd (service naam aangepast)")


def copy_html_files(src_dir: Path, dest_dir: Path):
    """Kopieer HTML files naar static directory."""
    src_static = src_dir / "static"
    dest_static = dest_dir

    if not src_static.exists():
        # Probeer parent/static
        src_static = src_dir.parent / "static"
        if not src_static.exists():
            print(f"WAARSCHUWING: static directory niet gevonden")
            return

    copied = 0
    for html_file in HTML_FILES:
        src = src_static / html_file
        if src.exists():
            shutil.copy2(src, dest_static / html_file)
            copied += 1
        else:
            print(f"  WAARSCHUWING: {html_file} niet gevonden in {src_static}")

    print(f"  {copied}/{len(HTML_FILES)} HTML files gekopieerd")

    # Check voor nieuwe HTML files die we mogelijk missen
    all_leef_html = list(src_static.glob("leef_*.html")) + list(
        src_static.glob("classificatie_*.html")
    )
    known = set(HTML_FILES)
    for f in all_leef_html:
        if f.name not in known:
            print(f"  NIEUW HTML BESTAND GEVONDEN: {f.name} - voeg toe aan HTML_FILES!")


def validate_routes(leef_code: str) -> int:
    """Tel het aantal @router routes in de geexporteerde code."""
    count = len(re.findall(r"@router\.(get|post|put|delete|patch)\(", leef_code))
    return count


def syntax_check(file_path: Path) -> bool:
    """Controleer Python syntax."""
    try:
        content = file_path.read_text(encoding="utf-8")
        compile(content, str(file_path), "exec")
        return True
    except SyntaxError as e:
        print(f"  SYNTAX FOUT in {file_path.name}: {e}")
        return False


def main():
    if len(sys.argv) < 2:
        print("Gebruik: python export_from_vergunningcheck.py <pad-naar-vergunningcheck>")
        print("Voorbeeld: python export_from_vergunningcheck.py ../vergunningcheck")
        sys.exit(1)

    vc_dir = find_vergunningcheck_dir(sys.argv[1])
    script_dir = Path(__file__).parent.resolve()
    app_dir = script_dir / "app"
    static_dir = script_dir / "static"

    # Maak directories aan
    app_dir.mkdir(exist_ok=True)
    static_dir.mkdir(exist_ok=True)

    print(f"=== LEEF Datashare Export ===")
    print(f"Bron:  {vc_dir}")
    print(f"Doel:  {script_dir}")
    print()

    # 1. Extract LEEF routes
    print("[1/6] LEEF routes extraheren uit geo_api.py...")
    geo_api = vc_dir / "geo_api.py"
    leef_block = extract_leef_block(geo_api)
    leef_routes_content = LEEF_ROUTES_IMPORTS + leef_block
    (app_dir / "leef_routes.py").write_text(leef_routes_content, encoding="utf-8")

    route_count = validate_routes(leef_routes_content)
    print(f"  {route_count} routes gevonden")
    if route_count < 15:
        print(f"  WAARSCHUWING: Verwacht minimaal 15 routes, slechts {route_count} gevonden!")

    # 2. Extract zaaktype mapping
    print("[2/6] Zaaktype mapping extraheren...")
    mapping = extract_zaaktype_mapping(geo_api)
    if mapping:
        (app_dir / "zaaktype_mapping.py").write_text(mapping, encoding="utf-8")
        entry_count = mapping.count("':")
        print(f"  {entry_count} zaaktype entries")

    # 3. Copy db_config.py
    print("[3/6] Database config...")
    copy_db_config(vc_dir, app_dir)

    # 4. Copy logging_config.py
    print("[4/6] Logging config...")
    copy_logging_config(vc_dir, app_dir)

    # 5. Copy HTML files
    print("[5/6] HTML files kopieren...")
    copy_html_files(vc_dir, static_dir)

    # 6. Validatie
    print("[6/6] Validatie...")
    errors = 0

    # Syntax check alle Python files
    for py_file in app_dir.glob("*.py"):
        if not syntax_check(py_file):
            errors += 1

    # Check dat alle verwachte bestanden bestaan
    expected_files = [
        app_dir / "api.py",
        app_dir / "leef_routes.py",
        app_dir / "zaaktype_mapping.py",
        app_dir / "db_config.py",
        app_dir / "logging_config.py",
        app_dir / "init_database.py",
    ]
    for f in expected_files:
        if not f.exists():
            print(f"  WAARSCHUWING: {f.name} ontbreekt!")
            errors += 1

    for html in HTML_FILES:
        if not (static_dir / html).exists():
            print(f"  WAARSCHUWING: {html} ontbreekt!")
            errors += 1

    print()
    if errors > 0:
        print(f"KLAAR met {errors} waarschuwing(en). Review de output hierboven.")
    else:
        print("KLAAR! Alle bestanden succesvol geexporteerd.")
        print()
        print("Volgende stappen:")
        print("  git diff              # Review wijzigingen")
        print("  git add . && git commit -m 'Sync from vergunningcheck'")


if __name__ == "__main__":
    main()
