# Zaaktype mapping: TEAG_CODE -> (Omschrijving, Domein, Soort, Anse_code)
_ZAAKTYPE_MAPPING = {
    'ADVS': ('Advies verstrekken (formeel)', 'Omgevingswet', 'Advies', 'LEEF'),
    'APV01': ('Evenementenvergunning', 'APV', 'Vergunning', 'LEEF'),
    'APV02': ('Alcoholwetvergunning', 'APV', 'Vergunning', 'LEEF'),
    'APV03': ('Collectevergunning', 'APV', 'Vergunning', 'LEEF'),
    'APV04': ('Exploitatievergunning', 'APV', 'Vergunning', 'LEEF'),
    'APV05': ('Loterijvergunning', 'APV', 'Vergunning', 'LEEF'),
    'APV06': ('Speelautomaten aanw.vergunning', 'APV', 'Vergunning', 'LEEF'),
    'APV07': ('Standplaatsvergunning', 'APV', 'Vergunning', 'LEEF'),
    'APV08': ('Terrasvergunning', 'APV', 'Vergunning', 'LEEF'),
    'APV09': ('Melding activiteit APV', 'APV', 'Melding', 'LEEF'),
    'APV10': ('Gedoogverklaring', 'APV', 'Vergunning', 'LEEF'),
    'APV11': ('Verklaring van geen bezwaar', 'APV', 'Vergunning', 'LEEF'),
    'APV12': ('Melding wijziging Alcoholwetv.', 'APV', 'Melding', 'LEEF'),
    'APV13': ('Melding incidentele fest.', 'APV', 'Melding', 'LEEF'),
    'APV14': ('Evenement melding', 'APV', 'Melding', 'LEEF'),
    'APV15': ('Kapmelding', 'APV', 'Melding', 'LEEF'),
    'APV16': ('Melding klein kansspel', 'APV', 'Melding', 'LEEF'),
    'APV17': ('Parkeerontheffing behandelen', 'APV', 'Vergunning', 'LEEF'),
    'APV18': ('Weekmarkt standplaatsverg', 'APV', 'Vergunning', 'LEEF'),
    'APV19': ('Melding paracommerci\u00eble act.', 'APV', 'Melding', 'LEEF'),
    'APV20': ('Wet Explosieven Civiel Gebruik', 'APV', 'Vergunning', 'LEEF'),
    'ASVN': ('Advies verstrekken/Vooroverleg', 'Omgevingswet', 'Vooroverleg', 'LEEF'),
    'AWOP': ('Aanvr wijzigen omgevingsplan', 'RO', 'RO-zaak', 'LEEF'),
    'BBBL': ('Zienswijze behandelen', 'Bezwaar en Beroep', 'Bezwaar en Beroep', 'BRBP'),
    'BBBP': ('Beroep behandelen', 'Bezwaar en Beroep', 'Bezwaar en Beroep', 'BRBP'),
    'BBBZ': ('Bezwaar behandelen', 'Bezwaar en Beroep', 'Bezwaar en Beroep', 'BRBP'),
    'BBHBP': ('Hoger beroep behandelen', 'Bezwaar en Beroep', 'Bezwaar en Beroep', 'BRBP'),
    'BBVV': ('Voorlopige voorziening beh.', 'Bezwaar en Beroep', 'Bezwaar en Beroep', 'BRBP'),
    'BGBG': ('Bodemsanering Beoordeling', 'Milieu', 'Overig', 'LEEF'),
    'BNSG': ('APV Stookontheffing', 'nvt', 'NIET IN GEBRUIK', 'BEWN'),
    'BTAG': ('Besluit ander bevoegd gezag', 'Omgevingswet', 'Overig', 'LEEF'),
    'BWBNRO': ('Bestemmingsplan', 'RO', 'RO-zaak', 'BWVG'),
    'BWGR': ('Geluidh. verhoging grenswaarde', 'RO', 'RO-zaak', 'BWVG'),
    'BWSEO': ('Exploitatieplan opstelling', 'RO', 'RO-zaak', 'BWVG'),
    'BWSHK': ('Haalbaarheidsonderz. - initiat', 'RO', 'RO-zaak', 'BWVG'),
    'BWSP': ('Principeverzoek', 'RO', 'RO-zaak', 'BWVG'),
    'BWSTP': ('Besch stads- of dorpsgez. aanp', 'Omgevingswet', 'Vergunning', 'BWVG'),
    'CEUN': ('Controle uitvoeren', 'Toezicht en handhaving', 'Controle', 'TTCE'),
    'HRBI': ('Huisnummer intrekking', 'Overig', 'Huisnummerbesluit', 'LEEF'),
    'HRBT': ('Huisnummer toekenning', 'Overig', 'Huisnummerbesluit', 'LEEF'),
    'HRBW': ('Huisnummer wijziging', 'Overig', 'Huisnummerbesluit', 'LEEF'),
    'IEVN': ('Informatieplicht behandelen', 'Omgevingswet', 'Melding', 'LEEF'),
    'INFB': ('Informatieverzoek door derde', 'Omgevingswet & APV', 'Vooroverleg', 'LEEF'),
    'INT': ('Vergunning/ontheffing intrekk.', 'Omgevingswet & APV', 'Vergunning', 'LEEF'),
    'MGAN': ('Melding activiteit behandelen', 'Omgevingswet', 'Melding', 'LEEF'),
    'MGOG03': ('Incidentmelding behandelen', 'Toezicht en handhaving', 'Klacht / Melding', 'TTCE'),
    'NEPE': ('Nadeelcompensatie/planschade', 'RO', 'RO-zaak', 'LEEF'),
    'ORMV': ('Omg.recht maatwerkvoorschrift', 'Omgevingswet', 'Vergunning', 'LEEF'),
    'OTHG': ('Ontheffing behandelen', 'Omgevingswet & APV', 'Vergunning', 'LEEF'),
    'REON': ('Ruimtelijke overeenkomsten', 'RO', 'RO-zaak', 'LEEF'),
    'TTCE1': ('Handhavingsbesluit nemen', 'Toezicht en handhaving', 'Handhaving', 'TTCE'),
    'TTCE3': ('Handhavingsverzoek behandelen', 'Toezicht en handhaving', 'Handhaving', 'TTCE'),
    'TTCE5': ('Last onder bestuursdwang uitv.', 'Toezicht en handhaving', 'Handhaving', 'TTCE'),
    'TTCE55': ('Last onder dwangsom uitv.', 'Toezicht en handhaving', 'Handhaving', 'TTCE'),
    'TTCE9': ('Handhaving opiumwet', 'Toezicht en handhaving', 'Handhaving', 'TTCE'),
    'VRGG': ('Omgevingsvergunning', 'Omgevingswet', 'Vergunning', 'LEEF'),
    'WO1F': ('Omgevingsverg 1e fase (WABO)', 'Omgevingswet', 'Vergunning', 'WABO'),
    'WO2F': ('Omgevingsverg 2e fase (WABO)', 'Omgevingswet', 'Vergunning', 'WABO'),
    'WOAG': ('Omgevingsvergunning (WABO)', 'Omgevingswet', 'Vergunning', 'WABO'),
    'WOMG': ('Melding behandelen (WABO)', 'Omgevingswet', 'Melding', 'WABO'),
    'WOP': ('Wijzigen Omgevingsplan', 'RO', 'RO-zaak', 'LEEF'),
    'WZ': ('Wijz. vergunning / ontheffing', 'Omgevingswet & APV', 'Vergunning', 'LEEF'),
}
